# Generated by Django 3.2.10 on 2022-01-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
