# Generated by Django 4.0.2 on 2022-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Employee_name',
            field=models.CharField(default='Python', max_length=120),
        ),
    ]
