# Generated by Django 4.0.2 on 2022-03-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_userprofile_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Employee_name',
        ),
    ]
